.TH HYP2MAT 1 local
.SH NAME
hyp2mat \- convert hyperlynx files to matlab scripts
.SH SYNOPSIS
.B hyp2mat
[
.BI \-o  " outfile"
] [
.BI \-f  " funcname"
] [
.BI \-h
] [
.B \-d
] 
infile
.SH DESCRIPTION
.I hyp2mat
converts Hyperlynx Signal-Integrity Transfer Format files to Octave/Matlab scripts.

Input files conventionally end in 
.BR .hyp
, while output files conventionally end in 
.BR .m
\&.

.I hyp2mat 
reads input from file
.IB infile . 
If no input file is specified input is read from standard in.

If a syntax error occurs during conversion, error recovery is attempted.
.I hyp2mat 
exits with zero status if conversion was succesful and non-zero if not.

Typical use is with simulation packages such as OpenEMS.

.SH OPTIONS
.TP
.BI \-o " outfile"
.br
.ns
Write output to file 
.IB outfile . 
If no output file is specified output is to standard out.

.TP
.BI \-f " funcname"
.br
.ns
Use function name 
.IB funcname 
for the generated code. 
If no function name is given, omit function declaration.

.TP
.B \-h
.br
.ns
Print usage summary and exit.

.TP
.B \-d
.br
.ns
Switch debugging on. 

A single
.B -d 
option switches scanner debugging on.  

A double
.B -d -d
option switches parser debugging on.

A triple
.B -d -d -d
option switches scanner and parser debugging on.  

.SH EXAMPLES
.TP 
Convert pcb.hyp to pcb.m:
.nf
hyp2mat -o pcb.m -f pcb pcb.hyp
.ni

.SH FILES
.TP
.B /usr/share/hyp2mat/matlab/
.br
.ns
Supporting matlab routines for OpenEMS.

.SH SEE ALSO
.IR octave (1)
.br
.IR "OpenEMS" ,
a free and open-source electromagnetic field solver using the FDTD method.

.SH AUTHOR
.nf
Koen De Vleeschauwer, http://www.kdvelectronics.eu
.ni
