/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt --unamed-opts

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Typical use of hyp2mat is with simulation packages such as OpenEMS.";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [-h] [ -o outfile ] [ -f pdf|csxcad ] [-n net]... [OPTIONS]... [-v] [infile]";

const char *gengetopt_args_info_description = "Converts Hyperlynx Signal-Integrity Transfer Format files to Octave/matlab \nscripts.";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                  Print help and exit",
  "  -V, --version               Print version and exit",
  "  -o, --output=filename       Output file.  (default=`-')",
  "  -f, --output-format=ENUM    Output file format.  (possible values=\"csxcad\", \n                                \"pdf\" default=`pdf')",
  "\nProcessing options:",
  "  -n, --net=STRING            Import named net. Repeat to import several nets. \n                                If no nets are specified all nets are imported.",
  "  -e, --epsilonr=DOUBLE       Set dielectric epsilon r. Overrides value in \n                                Hyperlynx file.",
  "  -x, --xmin=DOUBLE           Crop pcb. Set lowest value of x coordinate.",
  "  -X, --xmax=DOUBLE           Crop pcb. Set highest value of x coordinate.",
  "  -y, --ymin=DOUBLE           Crop pcb. Set lowest value of y coordinate.",
  "  -Y, --ymax=DOUBLE           Crop pcb. Set highest value of y coordinate.",
  "  -z, --zmin=DOUBLE           Crop pcb. Set lowest value of z coordinate.",
  "  -Z, --zmax=DOUBLE           Crop pcb. Set highest value of z coordinate.",
  "  -g, --grid=DOUBLE           Set output grid size.  (default=`10e-6')",
  "  -p, --arc-precision=DOUBLE  Set maximum difference between perfect arc and \n                                polygonal approximation.  (default=`0')",
  "\nPDF output options:",
  "      --hue=DOUBLE            Set PDF color hue. Range 0.0 to 1.0  \n                                (default=`0')",
  "      --saturation=DOUBLE     Set PDF color saturation. Range 0.0 to 1.0  \n                                (default=`0.6')",
  "      --brightness=DOUBLE     Set PDF color brightness. Range 0.0 to 1.0  \n                                (default=`0.9')",
  "\nDebugging options:",
  "  -r, --raw                   Raw output. Do not join adjacent or overlapping \n                                copper. Do not invert planes.  (default=off)",
  "  -d, --debug                 Increase debugging level. Repeat option for more \n                                detailed debugging.",
  "  -v, --verbose               Print board summary.",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_DOUBLE
  , ARG_ENUM
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_output_format_values[] = {"csxcad", "pdf", 0}; /*< Possible values for output-format. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->output_given = 0 ;
  args_info->output_format_given = 0 ;
  args_info->net_given = 0 ;
  args_info->epsilonr_given = 0 ;
  args_info->xmin_given = 0 ;
  args_info->xmax_given = 0 ;
  args_info->ymin_given = 0 ;
  args_info->ymax_given = 0 ;
  args_info->zmin_given = 0 ;
  args_info->zmax_given = 0 ;
  args_info->grid_given = 0 ;
  args_info->arc_precision_given = 0 ;
  args_info->hue_given = 0 ;
  args_info->saturation_given = 0 ;
  args_info->brightness_given = 0 ;
  args_info->raw_given = 0 ;
  args_info->debug_given = 0 ;
  args_info->verbose_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->output_arg = gengetopt_strdup ("-");
  args_info->output_orig = NULL;
  args_info->output_format_arg = output_format_arg_pdf;
  args_info->output_format_orig = NULL;
  args_info->net_arg = NULL;
  args_info->net_orig = NULL;
  args_info->epsilonr_orig = NULL;
  args_info->xmin_orig = NULL;
  args_info->xmax_orig = NULL;
  args_info->ymin_orig = NULL;
  args_info->ymax_orig = NULL;
  args_info->zmin_orig = NULL;
  args_info->zmax_orig = NULL;
  args_info->grid_arg = 10e-6;
  args_info->grid_orig = NULL;
  args_info->arc_precision_arg = 0;
  args_info->arc_precision_orig = NULL;
  args_info->hue_arg = 0;
  args_info->hue_orig = NULL;
  args_info->saturation_arg = 0.6;
  args_info->saturation_orig = NULL;
  args_info->brightness_arg = 0.9;
  args_info->brightness_orig = NULL;
  args_info->raw_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->output_help = gengetopt_args_info_help[2] ;
  args_info->output_format_help = gengetopt_args_info_help[3] ;
  args_info->net_help = gengetopt_args_info_help[5] ;
  args_info->net_min = 0;
  args_info->net_max = 0;
  args_info->epsilonr_help = gengetopt_args_info_help[6] ;
  args_info->xmin_help = gengetopt_args_info_help[7] ;
  args_info->xmax_help = gengetopt_args_info_help[8] ;
  args_info->ymin_help = gengetopt_args_info_help[9] ;
  args_info->ymax_help = gengetopt_args_info_help[10] ;
  args_info->zmin_help = gengetopt_args_info_help[11] ;
  args_info->zmax_help = gengetopt_args_info_help[12] ;
  args_info->grid_help = gengetopt_args_info_help[13] ;
  args_info->arc_precision_help = gengetopt_args_info_help[14] ;
  args_info->hue_help = gengetopt_args_info_help[16] ;
  args_info->saturation_help = gengetopt_args_info_help[17] ;
  args_info->brightness_help = gengetopt_args_info_help[18] ;
  args_info->raw_help = gengetopt_args_info_help[20] ;
  args_info->debug_help = gengetopt_args_info_help[21] ;
  args_info->debug_min = 0;
  args_info->debug_max = 0;
  args_info->verbose_help = gengetopt_args_info_help[22] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    double double_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}


static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->output_format_orig));
  free_multiple_string_field (args_info->net_given, &(args_info->net_arg), &(args_info->net_orig));
  free_string_field (&(args_info->epsilonr_orig));
  free_string_field (&(args_info->xmin_orig));
  free_string_field (&(args_info->xmax_orig));
  free_string_field (&(args_info->ymin_orig));
  free_string_field (&(args_info->ymax_orig));
  free_string_field (&(args_info->zmin_orig));
  free_string_field (&(args_info->zmax_orig));
  free_string_field (&(args_info->grid_orig));
  free_string_field (&(args_info->arc_precision_orig));
  free_string_field (&(args_info->hue_orig));
  free_string_field (&(args_info->saturation_orig));
  free_string_field (&(args_info->brightness_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->output_format_given)
    write_into_file(outfile, "output-format", args_info->output_format_orig, cmdline_parser_output_format_values);
  write_multiple_into_file(outfile, args_info->net_given, "net", args_info->net_orig, 0);
  if (args_info->epsilonr_given)
    write_into_file(outfile, "epsilonr", args_info->epsilonr_orig, 0);
  if (args_info->xmin_given)
    write_into_file(outfile, "xmin", args_info->xmin_orig, 0);
  if (args_info->xmax_given)
    write_into_file(outfile, "xmax", args_info->xmax_orig, 0);
  if (args_info->ymin_given)
    write_into_file(outfile, "ymin", args_info->ymin_orig, 0);
  if (args_info->ymax_given)
    write_into_file(outfile, "ymax", args_info->ymax_orig, 0);
  if (args_info->zmin_given)
    write_into_file(outfile, "zmin", args_info->zmin_orig, 0);
  if (args_info->zmax_given)
    write_into_file(outfile, "zmax", args_info->zmax_orig, 0);
  if (args_info->grid_given)
    write_into_file(outfile, "grid", args_info->grid_orig, 0);
  if (args_info->arc_precision_given)
    write_into_file(outfile, "arc-precision", args_info->arc_precision_orig, 0);
  if (args_info->hue_given)
    write_into_file(outfile, "hue", args_info->hue_orig, 0);
  if (args_info->saturation_given)
    write_into_file(outfile, "saturation", args_info->saturation_orig, 0);
  if (args_info->brightness_given)
    write_into_file(outfile, "brightness", args_info->brightness_orig, 0);
  if (args_info->raw_given)
    write_into_file(outfile, "raw", 0, 0 );
  write_multiple_into_file(outfile, args_info->debug_given, "debug", 0, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->net_given, args_info->net_min, args_info->net_max, "'--net' ('-n')"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->debug_given, args_info->debug_min, args_info->debug_max, "'--debug' ('-d')"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_ENUM:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_DOUBLE:
      *((double **)field) = (double *)realloc (*((double **)field), (field_given + prev_given) * sizeof (double)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_DOUBLE:
          (*((double **)field))[i + field_given] = tmp->arg.double_arg; break;
        case ARG_ENUM:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_ENUM:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_DOUBLE:
        if (! *((double **)field)) {
          *((double **)field) = (double *)malloc (sizeof (double));
          (*((double **)field))[0] = default_value->double_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * net_list = NULL;
  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "output",	1, NULL, 'o' },
        { "output-format",	1, NULL, 'f' },
        { "net",	1, NULL, 'n' },
        { "epsilonr",	1, NULL, 'e' },
        { "xmin",	1, NULL, 'x' },
        { "xmax",	1, NULL, 'X' },
        { "ymin",	1, NULL, 'y' },
        { "ymax",	1, NULL, 'Y' },
        { "zmin",	1, NULL, 'z' },
        { "zmax",	1, NULL, 'Z' },
        { "grid",	1, NULL, 'g' },
        { "arc-precision",	1, NULL, 'p' },
        { "hue",	1, NULL, 0 },
        { "saturation",	1, NULL, 0 },
        { "brightness",	1, NULL, 0 },
        { "raw",	0, NULL, 'r' },
        { "debug",	0, NULL, 'd' },
        { "verbose",	0, NULL, 'v' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVo:f:n:e:x:X:y:Y:z:Z:g:p:rdv", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'o':	/* Output file..  */
        
        
          if (update_arg( (void *)&(args_info->output_arg), 
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, "-", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Output file format..  */
        
        
          if (update_arg( (void *)&(args_info->output_format_arg), 
               &(args_info->output_format_orig), &(args_info->output_format_given),
              &(local_args_info.output_format_given), optarg, cmdline_parser_output_format_values, "pdf", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "output-format", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Import named net. Repeat to import several nets. If no nets are specified all nets are imported..  */
        
          if (update_multiple_arg_temp(&net_list, 
              &(local_args_info.net_given), optarg, 0, 0, ARG_STRING,
              "net", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* Set dielectric epsilon r. Overrides value in Hyperlynx file..  */
        
        
          if (update_arg( (void *)&(args_info->epsilonr_arg), 
               &(args_info->epsilonr_orig), &(args_info->epsilonr_given),
              &(local_args_info.epsilonr_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "epsilonr", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* Crop pcb. Set lowest value of x coordinate..  */
        
        
          if (update_arg( (void *)&(args_info->xmin_arg), 
               &(args_info->xmin_orig), &(args_info->xmin_given),
              &(local_args_info.xmin_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "xmin", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'X':	/* Crop pcb. Set highest value of x coordinate..  */
        
        
          if (update_arg( (void *)&(args_info->xmax_arg), 
               &(args_info->xmax_orig), &(args_info->xmax_given),
              &(local_args_info.xmax_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "xmax", 'X',
              additional_error))
            goto failure;
        
          break;
        case 'y':	/* Crop pcb. Set lowest value of y coordinate..  */
        
        
          if (update_arg( (void *)&(args_info->ymin_arg), 
               &(args_info->ymin_orig), &(args_info->ymin_given),
              &(local_args_info.ymin_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "ymin", 'y',
              additional_error))
            goto failure;
        
          break;
        case 'Y':	/* Crop pcb. Set highest value of y coordinate..  */
        
        
          if (update_arg( (void *)&(args_info->ymax_arg), 
               &(args_info->ymax_orig), &(args_info->ymax_given),
              &(local_args_info.ymax_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "ymax", 'Y',
              additional_error))
            goto failure;
        
          break;
        case 'z':	/* Crop pcb. Set lowest value of z coordinate..  */
        
        
          if (update_arg( (void *)&(args_info->zmin_arg), 
               &(args_info->zmin_orig), &(args_info->zmin_given),
              &(local_args_info.zmin_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "zmin", 'z',
              additional_error))
            goto failure;
        
          break;
        case 'Z':	/* Crop pcb. Set highest value of z coordinate..  */
        
        
          if (update_arg( (void *)&(args_info->zmax_arg), 
               &(args_info->zmax_orig), &(args_info->zmax_given),
              &(local_args_info.zmax_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "zmax", 'Z',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Set output grid size..  */
        
        
          if (update_arg( (void *)&(args_info->grid_arg), 
               &(args_info->grid_orig), &(args_info->grid_given),
              &(local_args_info.grid_given), optarg, 0, "10e-6", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "grid", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Set maximum difference between perfect arc and polygonal approximation..  */
        
        
          if (update_arg( (void *)&(args_info->arc_precision_arg), 
               &(args_info->arc_precision_orig), &(args_info->arc_precision_given),
              &(local_args_info.arc_precision_given), optarg, 0, "0", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "arc-precision", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Raw output. Do not join adjacent or overlapping copper. Do not invert planes..  */
        
        
          if (update_arg((void *)&(args_info->raw_flag), 0, &(args_info->raw_given),
              &(local_args_info.raw_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "raw", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Increase debugging level. Repeat option for more detailed debugging..  */
        
          local_args_info.debug_given++;
        
          break;
        case 'v':	/* Print board summary..  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Set PDF color hue. Range 0.0 to 1.0.  */
          if (strcmp (long_options[option_index].name, "hue") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->hue_arg), 
                 &(args_info->hue_orig), &(args_info->hue_given),
                &(local_args_info.hue_given), optarg, 0, "0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "hue", '-',
                additional_error))
              goto failure;
          
          }
          /* Set PDF color saturation. Range 0.0 to 1.0.  */
          else if (strcmp (long_options[option_index].name, "saturation") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->saturation_arg), 
                 &(args_info->saturation_orig), &(args_info->saturation_given),
                &(local_args_info.saturation_given), optarg, 0, "0.6", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "saturation", '-',
                additional_error))
              goto failure;
          
          }
          /* Set PDF color brightness. Range 0.0 to 1.0.  */
          else if (strcmp (long_options[option_index].name, "brightness") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->brightness_arg), 
                 &(args_info->brightness_orig), &(args_info->brightness_given),
                &(local_args_info.brightness_given), optarg, 0, "0.9", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "brightness", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->net_arg),
    &(args_info->net_orig), args_info->net_given,
    local_args_info.net_given, 0,
    ARG_STRING, net_list);

  args_info->net_given += local_args_info.net_given;
  local_args_info.net_given = 0;
  args_info->debug_given += local_args_info.debug_given;
  local_args_info.debug_given = 0;
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  free_list (net_list, 1 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
